Repository 100-hours-a-week/1-team-YouTIL-be, pull requests merged in 2025-05, with the labels that each got.

#38 [feat] 이미지 호스팅(GCP) 추가
  .gitignore
  build.gradle
  src/main/java/com/youtil/Api/Storage/Controller/StorageController.java
  src/main/java/com/youtil/Api/Storage/Dto/StorageResponseDTO.java
  src/main/java/com/youtil/Api/Storage/Service/StorageService.java
  src/main/java/com/youtil/Config/GcpStorageConfig.java
Labels: :goose: [feat]

#49 [fix]스토리지 서비스상태코드 상수화
  src/main/java/com/youtil/Api/Storage/Service/StorageService.java
  src/main/java/com/youtil/Common/Enums/ErrorMessageCode.java
  src/main/java/com/youtil/Exception/StorageException/StorageException.java
  src/main/java/com/youtil/Exception/StorageException/StorageExceptionController.java
Labels: :hammer: [fix]

#63 [fix] corsConfig 수정
  .gitignore
  src/main/java/com/youtil/Config/CorsConfig.java
Labels: :hammer: [fix]

#69 [fix] 자신의 til 조회하는 것 수정
  src/main/java/com/youtil/Repository/TilRepositoryCustomImpl.java
Labels: :hammer: [fix]

#77 [fix] 뉴스이미지 포맷팅 및 프록시 적용
  src/main/java/com/youtil/Api/News/Controller/NewsController.java
  src/main/java/com/youtil/Api/News/Converter/NewsConverter.java
  src/main/java/com/youtil/Api/News/Service/NewsService.java
  src/main/java/com/youtil/Config/AppProperties.java
  src/main/java/com/youtil/Config/SecurityConfig.java
  src/main/java/com/youtil/Config/WebClientConfig.java
Labels: :hammer: [fix]

#78 Prod 배포
  src/main/java/com/youtil/Api/News/Controller/NewsController.java
  src/main/java/com/youtil/Api/News/Converter/NewsConverter.java
  src/main/java/com/youtil/Api/News/Service/NewsService.java
  src/main/java/com/youtil/Config/AppProperties.java
  src/main/java/com/youtil/Config/SecurityConfig.java
  src/main/java/com/youtil/Config/WebClientConfig.java
Labels: :hammer: [fix]

#91 [fix] 프로메테우스 토큰 예외처리
  src/main/java/com/youtil/Config/SecurityConfig.java
Labels: :goose: [feat]

#92 [fix] 프로메테우스 토큰 예외처리
  src/main/java/com/youtil/Config/SecurityConfig.java
Labels: :hammer: [fix]

#95 Dev
  src/main/java/com/youtil/Api/Github/Controller/GithubController.java
  src/main/java/com/youtil/Api/Github/Converter/GitHubDtoConverter.java
  src/main/java/com/youtil/Api/Github/Dto/GithubResponseDTO.java
  src/main/java/com/youtil/Api/Github/Service/GithubCommitDetailService.java
  src/main/java/com/youtil/Api/Github/Service/GithubCommitSummaryService.java
  src/main/java/com/youtil/Api/Github/Service/GithubService.java
  src/main/java/com/youtil/Config/SwaggerConfig.java
  src/main/java/com/youtil/Security/JwtAuthenticationFilter.java
Labels: :hammer: [fix]

#84 [feat] TIL AI 서버 상태 체크하는 API 구현
  src/main/java/com/youtil/Api/Tils/Controller/TilReadController.java
  src/main/java/com/youtil/Api/Tils/Service/TilAiService.java
  src/main/java/com/youtil/Api/Tils/Service/TilCommendService.java
  src/main/java/com/youtil/Common/Enums/ErrorMessageCode.java
  src/main/java/com/youtil/Common/Enums/MessageCode.java
  src/main/java/com/youtil/Common/Enums/TilMessageCode.java
  src/main/java/com/youtil/Config/SwaggerConfig.java
  src/main/java/com/youtil/Exception/TilException/TilException.java
  src/main/java/com/youtil/Exception/TilException/TilExceptionController.java
Labels: :goose: [feat]

#119 [feat] User 도메인 테스트코드 작성
  src/main/java/com/youtil/Api/User/Dto/GithubResponseDTO.java
  src/main/java/com/youtil/Api/User/Service/UserService.java
  src/main/java/com/youtil/Util/JwtUtil.java
  src/test/java/com/youtil/Api/User/Service/UserServiceTest.java
  src/test/java/com/youtil/Constants/MockTilConstants.java
  src/test/java/com/youtil/Constants/MockUserConstants.java
  src/test/java/com/youtil/Constants/UserServiceConstants.java
  src/test/java/com/youtil/Mock/MockTilBuilder.java
  src/test/java/com/youtil/Mock/MockUserBuilder.java
Labels: :test_tube: test

#121 [feat] 뉴스 도메인 테스트 코드 작성
  src/main/java/com/youtil/Api/Storage/Service/StorageService.java
  src/test/java/com/youtil/Constants/MockNewsConstants.java
  src/test/java/com/youtil/Constants/NewsServiceTestConstants.java
  src/test/java/com/youtil/Mock/MockNewsBuilder.java
  src/test/java/com/youtil/News/Service/NewsServiceTest.java
  src/test/java/com/youtil/Util/MockUtil.java
Labels: :test_tube: test

#139 Dev
  src/main/java/com/youtil/Api/Storage/Service/StorageService.java
  src/main/java/com/youtil/Config/SecurityConfig.java
  src/main/java/com/youtil/Config/SecuritySwaggerBlockConfig.java
  src/main/java/com/youtil/Config/SwaggerConfig.java
  src/test/java/com/youtil/Constants/MockNewsConstants.java
  src/test/java/com/youtil/Constants/NewsServiceTestConstants.java
  src/test/java/com/youtil/Mock/MockNewsBuilder.java
  src/test/java/com/youtil/News/Service/NewsServiceTest.java
  src/test/java/com/youtil/Util/MockUtil.java
Labels: :hammer: [fix]
