Repository 100-hours-a-week/1-team-YouTIL-be, pull requests merged in 2025-07, with the labels that each got.

#262 [feat] jacoco 커버지리 적용
  build.gradle
  src/test/java/com/youtil/News/Service/NewsServiceTest.java
Labels: :goose: [feat]

#150 [FEAT] TIL 도메인 테스트 코드 작성
  src/main/java/com/youtil/Api/Github/Service/GithubCommitDetailService.java
  src/main/java/com/youtil/Api/Github/Service/GithubCommitSummaryService.java
  src/main/java/com/youtil/Api/Tils/Service/TilAiService.java
  src/test/java/com/youtil/Api/Community/Service/CommunityServiceTest.java
  src/test/java/com/youtil/Api/Github/Service/GithubCommitServiceTest.java
  src/test/java/com/youtil/Api/Github/Service/GithubServiceTest.java
  src/test/java/com/youtil/Api/Tils/Service/TilAiServiceTest.java
  src/test/java/com/youtil/Api/Tils/Service/TilCrudServiceTest.java
  src/test/java/com/youtil/Constants/MockGitHubConstants.java
  src/test/java/com/youtil/Constants/MockTilConstants.java
  src/test/java/com/youtil/Constants/MockUserConstants.java
  src/test/java/com/youtil/Mock/MockGitHubBuilder.java
  src/test/java/com/youtil/Mock/MockTilBuilder.java
  src/test/java/com/youtil/Util/MockUtil.java
Labels: :test_tube: test

#305 [fix] S3 스토리지 전환
  build.gradle
  src/main/java/com/youtil/Api/Storage/Controller/StorageController.java
  src/main/java/com/youtil/Api/Storage/Service/StorageService.java
  src/main/java/com/youtil/Config/Storage/GcpStorageConfig.java
  src/main/java/com/youtil/Config/Storage/S3Config.java
  src/main/java/com/youtil/Config/StorageConfig.java
  src/test/java/com/youtil/Api/Storage/Service/StorageServiceTest.java
Labels: :goose: [feat]

#308 [fix] GCS 삭제
  build.gradle
  src/main/java/com/youtil/Api/Interview/Handler/InterviewDispatcherWorker.java
  src/main/java/com/youtil/Api/Storage/Service/StorageService.java
  src/main/java/com/youtil/Api/Tils/Handler/TilDispatcherWorker.java
  src/main/java/com/youtil/Config/Storage/GcpStorageConfig.java
  src/main/java/com/youtil/Config/Storage/S3Config.java
  src/main/java/com/youtil/Config/StorageConfig.java
  src/main/java/com/youtil/Config/TimeZoneConfig.java
  src/test/java/com/youtil/Api/Storage/Service/StorageServiceTest.java
  src/test/java/com/youtil/Constants/StorageServiceTestConstants.java
Labels: :computer: [ci/cd]

#315 Dev
  src/main/java/com/youtil/Api/Github/Service/GithubCommitCalendarService.java
  src/main/java/com/youtil/Api/News/Converter/NewsConverter.java
  src/main/java/com/youtil/Api/News/Service/NewsService.java
  src/main/java/com/youtil/Api/Storage/Service/StorageService.java
  src/main/java/com/youtil/Api/Tils/Queue/TilQueConsumer.java
  src/main/java/com/youtil/Common/Sse/SseEmitterService.java
Labels: :computer: [ci/cd]
